### ISSUE TITLE
Images with build-essential for packages with binary dependencies

### ISSUE THREAD

**Issue by jpfairbanks** [docker-library/julia#12]
Does it make sense to ship a version of these docker images with build-essential so that things with binary dependencies have a compiler and such? 

Pros:
  - Pkg.add works with some binary dependencies out of the box

Cons:
  - Larger image sizes than strictly necessary
  - All you save is "run(\`apt update\` & \`apt install build-essential\`)"

**Comment by giordano** [comment]
I believe the need for a compiler in the image is much reduced for the most recent versions of Julia (v1.3+).

**Comment by tianon** [comment]
Oops, sorry for leaving this one for so long!  Glad it's ~resolved itself reasonably, however. :sweat_smile: :+1:
