### ISSUE TITLE
support arm64 architecture

### ISSUE THREAD

**Issue by longquan7** [docker-library/julia#14]
I want to build this image on arm64 architecture,but I don't know this file whether or not support arm64 architecture with https://julialang-s3.julialang.org/bin/linux/arm/0.6/julia-0.6.0-pre.beta-linux-arm.tar.gz.

**Comment by tianon** [comment]
See https://github.com/docker-library/julia/pull/15 -- currently, only `amd64`, `arm32v7`, and `i386` are supported by Julia upstream, but `ppc64le` and `arm64v8` are currently in development (and might show up with a future release).

**Comment by longquan7** [comment]
@tianon OK,thanks
