### ISSUE TITLE
Update windows base images

### ISSUE THREAD

**Issue by J0WI** [docker-library/julia#34]
E.g. `ltsc2019`

**Comment by tianon** [comment]
Isn't `ltsc2019` still the same as `1809`?

**Comment by J0WI** [comment]
You're right. How about replacing `1803` with `1903` then?

**Comment by tianon** [comment]
https://github.com/docker-library/golang/pull/289#issuecomment-509841894 :disappointed:

**Comment by yosifkit** [comment]
> We have set up a fresh new Server 2022 builder to replace our existing 2019 builder.  We can now handle `Constraints: windowsservercore-ltsc2022` and/or `nanoserver-ltsc2022`. :+1:
>
> \- https://github.com/docker-library/official-images/issues/9198#issuecomment-904994195
