### ISSUE TITLE
Newer julia version for debian stretch

### ISSUE THREAD

**Issue by blaiseli** [docker-library/julia#35]
Dear container maintainers,

I would like to containerize a Julia application with singularity in order to run it on a computing cluster. Unfortunately, the kernel of the computing cluster is too old to run debian buster based images.

I saw that you provided a stretch based image for Julia 1.0, but the application is not compatible with julia 1.0.

Would it be possible to add stretch based containers for newer Julia versions ?

Thanks in advance.

**Comment by blaiseli** [comment]
Thanks for your quick action. Do you know when the new images will be available on the docker hub ?

**Comment by yosifkit** [comment]
@blaiseli, see https://github.com/docker-library/faq/#an-images-source-changed-in-git-now-what
