### ISSUE TITLE
[julia-1.3.0] Not properly signed for the macOS 10.15 (Catalina)

### ISSUE THREAD

**Issue by conradwt** [docker-library/julia#38]
Julia's application bundle hasn't been properly signed for macOS 10.15 (Catalina).  Thus, it will not automatically launch and one must go to **System Preferences -> Security & Privacy -> General Tab and click Open Anyway** in order to successfully launch the binary executable.  Next, one can find the steps to properly sign a binary executable by going to the following page:

https://developer.apple.com/developer-id

Finally, System Preferences is great to get things up and operational but I believe a long term strategy should be to sign the application bundle.  If signing the application bundle isn't an option, this should be documented as to why it's not being signed and how System Preferences should be used for end-users.

**Comment by wglambert** [comment]
This repo is for the Docker image Julia 

You're probably looking for https://github.com/JuliaLang/julia/issues/33331 https://github.com/JuliaLang/julia/issues/33540 https://github.com/JuliaLang/julia/issues/33141
