### ISSUE TITLE
"Cannot change ownership" when trying to install FFTW

### ISSUE THREAD

**Issue by fjarri** [docker-library/julia#39]
When installing FFTW inside a container (as a part of the project's dependencies), I get a bunch of the following errors:
```
tar: ./include/fftw3.f: Cannot change ownership to uid 261840, gid 261840: Invalid argument
tar: ./include/fftw3.f03: Cannot change ownership to uid 261840, gid 261840: Invalid argument
...
```

The problem only exists in the julia-1.3 container; julia-1.0 and julia-1.2 work fine.

**Comment by fredrikekre** [comment]
@staticfloat ^

Probably not an issue with the docker image per se, but rather an issue with how julia installs artifacts (e.g. how we assume what permissions the package installayion has).

**Comment by fredrikekre** [comment]
Same issue as https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/555 which will be fixed by https://github.com/JuliaLang/Pkg.jl/pull/1557

**Comment by tianon** [comment]
Nice!  That's something that needs a new release of Julia 1.3 for folks to see the fix though, right?  (Trying to gauge whether we should close this or leave it open until the next release. :sweat_smile:)

**Comment by fredrikekre** [comment]
Yea, this can be closed IMO.

**Comment by EricForgy** [comment]
Oh man. I burned 3 days struggling with this issue. Glad to see it fixed and look forward to a new release 🙏
