### ISSUE TITLE
Version 1.3.1 for arm32v7 is not yet available

### ISSUE THREAD

**Issue by giordano** [docker-library/julia#40]
Running a Drone job on arm32v7 fails because the image is not available: https://cloud.drone.io/JuliaMath/SpecialFunctions.jl/115/1/2.  The 1.3.1-buster tag in [the Dockerhub page](https://hub.docker.com/_/julia/) points to [this Dockerfile](https://github.com/docker-library/julia/blob/92acb5e96f5e19a2dd4955eb478ed74d31ed5059/1.3/buster/Dockerfile) which doesn't contain [this commit](https://github.com/docker-library/julia/commit/decfcd314ded05c1afc5202ec423a31e4f959635).

**Comment by wglambert** [comment]
https://github.com/docker-library/julia#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet

Most recent image update was 4 days ago https://github.com/docker-library/official-images/pulls?q=is%3Apr+label%3Alibrary%2Fjulia+is%3Aclosed

**Comment by wglambert** [comment]
The update will be propagated to the hub shortly after this merges https://github.com/docker-library/official-images/pull/7240
