### ISSUE TITLE
arm64v8 builds not updating

### ISSUE THREAD

**Issue by staticfloat** [docker-library/julia#53]
The 1.6.0-beta1 and 1.6.0-rc1 builds do not appear to have an arm64v8 build available, while the 1.5.X builds do.

**Comment by tianon** [comment]
It seems our build server is having trouble downloading the artifacts? :confused:

```console
+ curl -fL -o julia.tar.gz.asc https://julialang-s3.julialang.org/bin/linux/aarch64/1.6/julia-1.6.0-rc1-linux-aarch64.tar.gz.asc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to ewr1-cache.e.ip.saba.us port 443: Connection refused
```

(Although if I hit that URL locally, it downloads just fine. :confused:)

**Comment by tianon** [comment]
I got slightly more data doing it interactively:

```console
root@90f22ee01963:/# curl -fL -D- -o julia.tar.gz.asc https://julialang-s3.julialang.org/bin/linux/aarch64/1.6/julia-1.6.0-rc1-linux-aarch64.tar.gz.asc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0HTTP/2 302 
server: Varnish
retry-after: 0
location: https://ewr1-cache.e.ip.saba.us/julialang2/bin/linux/aarch64/1.6/julia-1.6.0-rc1-linux-aarch64.tar.gz.asc
accept-ranges: bytes
date: Tue, 09 Feb 2021 20:15:41 GMT
via: 1.1 varnish
x-served-by: cache-lga21958-LGA
x-cache: HIT
x-cache-hits: 0
x-timer: S1612901741.008251,VS0,VE1
content-length: 0

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to ewr1-cache.e.ip.saba.us port 443: Connection refused
```

**Comment by staticfloat** [comment]
Ah, seems we had some caching trouble.  Can you try again now please?

**Comment by tianon** [comment]
My own build on a different (testing) daemon on that same server was successful!

For the official build, this should get picked up by https://doi-janky.infosiftr.net/job/multiarch/job/arm64v8/job/julia/218/console (which should happen as soon as https://doi-janky.infosiftr.net/job/multiarch/job/arm64v8/job/gcc/226/console finishes, hopefully within the next hour or so).

**Comment by staticfloat** [comment]
You're a legend.  Thanks @tianon!

**Comment by tianon** [comment]
Just for posterity, `arm32v7` was affected by this also (it's built on the same server), and so when it finally gets some queue time it should hopefully be fixed too. :+1:

(https://github.com/docker-library/official-images/pull/9590 updated `debian` which always does a number on our queues, so it's gonna take some time to work back through :sweat_smile:)

**Comment by giordano** [comment]
Unfortunately there is no build for armv7l  😞

**Comment by tianon** [comment]
Oh!  I guess that's just for 1.0, sorry (but same underlying build failure). :grimacing:
