### ISSUE TITLE
Julia v1.6.1 on armv7l

### ISSUE THREAD

**Issue by giordano** [docker-library/julia#55]
After a log time, Julia v1.6.1 has finally an official build for armv7l: https://julialang.org/downloads/#current_stable_release.  Is there something that needs to be enabled here to build the Docker images for this platform?  It doesn't seem to be available at the moment, as far as I can see.

**Comment by staticfloat** [comment]
Sorry about that @tianon, can you try again now?

**Comment by giordano** [comment]
That was fast, thanks everybody! :pray:
