### ISSUE TITLE
Julia 1.7.2

### ISSUE THREAD

**Issue by rikhuijzer** [docker-library/julia#64]
The docker image is still on Julia 1.7.1 while the binaries for 1.7.2 are available at https://julialang.org/downloads/. The official announcement on Discourse was yesterday (https://discourse.julialang.org/t/julia-v1-7-2-has-been-released/75994).

**Comment by ImreSamu** [comment]
in progress :-)

now updated to 1.7.2 :  https://github.com/docker-library/julia/commit/c18dc57da4780a32746fbfcc34ba17f45dc5f5d7
so we have to wait ( ~1-2 workday )  https://github.com/docker-library/julia#see-a-change-merged-here-that-doesnt-show-up-on-docker-

**Comment by ImreSamu** [comment]
@rikhuijzer :smile:   ready for the experiments : https://hub.docker.com/_/julia?tab=tags&page=1&name=1.7.2
