### ISSUE TITLE
Shared tag for upcoming releases

### ISSUE THREAD

**Issue by vinzenz-muser** [docker-library/julia#66]
Is there a possibility to get a shared tag for upcoming releases? We want to be sure that our program will work on the upcoming versions of Julia all the time, so we build it with the latest version and also with the upcoming version. Currently, we have to keep that upcoming version manually up to date, so for example currently we have to use '1.8-rc-buster' but as soon as a 1.9 version will come out, we'll have to change it again. An 'upcoming'-tag or something similar would be great.

**Comment by tianon** [comment]
We used to maintain an "`rc`" alias - I guess that would probably meet your needs?  Over time it will come and go from the "supported" list, but would always point to whatever the most recent "rc" was.

**Comment by vinzenz-muser** [comment]
Yes, that would work perfectly if it always points to the most recent rc! But I don't understand completely what you mean by "it will come and go from the supported list": Does that mean it is not reliable to use?

**Comment by yosifkit** [comment]
The `rc` tag would still be available to `docker pull`, but when there isn't an active pre-release, it wouldn't be updated or rebuilt for base image changes. (It would come and go from our [`library/julia` file](https://github.com/docker-library/official-images/blob/f1103e86be3c826644771a5736a8288d1940b979/library/julia) that controls which are actively built and also which show up on the Docker Hub readme page under "Supported tags and respective Dockerfile links")
