### ISSUE TITLE
Use ENTRYPOINT instead of CMD

### ISSUE THREAD

**Issue by maleadt** [docker-library/julia#71]
It is convenient to be able to treat `docker run --rm -it julia` just as you would use the `julia` binary. This is currently not possible, because the containers here set CMD and not ENTRYPOINT:

```
❯ docker run --rm -it julia -e '42'
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "-e": executable file not found in $PATH: unknown.
```

**Comment by tianon** [comment]
Unfortunately, we can't just swap to `ENTRYPOINT` as-is (https://github.com/docker-library/official-images#consistency), but we _can_ write a script that fixes the problem -- thanks for raising it!  (I'll get to work on a PR :heart:)

**Comment by maleadt** [comment]
Ah, interesting! Thanks for the PR, the entrypoint script should cover most common cases.
