### ISSUE TITLE
Support for AmazonLinux 2

### ISSUE THREAD

**Issue by mattBrzezinski** [docker-library/julia#73]
We at [Invenia](https://github.com/invenia) currently have a closed source build of Julia on [amazonlinux:2](https://hub.docker.com/_/amazonlinux). I was curious if we could get support officially for this, alternatively I would not mind learning and porting what we have to this package (might need some guidance on that).

**Comment by tianon** [comment]
I don't know that we want to expand the "official" support matrix much (unless we have something like the Julia project officially recommending Amazon Linux as the "best-supported" distribution or something), but I bet you could get pretty far by doing something like:

```dockerfile
FROM amazonlinux:2
ENV JULIA_PATH /usr/local/julia
ENV PATH $JULIA_PATH/bin:$PATH
COPY --from=julia:1.8 $JULIA_PATH $JULIA_PATH
```

```console
$ docker run --rm 35473a39cf47 julia --version
julia version 1.8.2
```

**Comment by mattBrzezinski** [comment]
That’s perfectly fine! The other use case would be for supporting Julia Docker images on AWS Lambda more easily,

https://github.com/JuliaCloud/LambdaMaker.jl

feel free to close this issue if you see fit!

**Comment by tianon** [comment]
Thanks - I'm going to close this for now, but hopefully it serves as a useful reference for folks in the future. :+1:
